"""baseline schema

The whole database as it stood when migrations were introduced: all nine
tables, generated by ``alembic revision --autogenerate`` against an empty
schema and checked by hand.

A brand-new database is built by running this. A database that already
existed before migrations (created by the old start-up code) is instead
brought up to this point by migrate.py and then *stamped* as 0001 -- marked
as already having it, without running it -- because its tables are already
there.

Revision ID: 0001
Revises:
Create Date: 2026-09-12 11:23:58.097288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _create_users() -> None:
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)


def _create_cvs() -> None:
    op.create_table('cvs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('profile_json', sa.Text(), nullable=True),
    sa.Column('profile_version', sa.Integer(), nullable=True),
    sa.Column('profile_parsed_at', sa.DateTime(), nullable=True),
    sa.Column('embedding', sa.Text(), nullable=True),
    sa.Column('embedding_version', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cvs_id'), 'cvs', ['id'], unique=False)


def _create_jobs() -> None:
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('employment_type', sa.String(length=50), nullable=False),
    sa.Column('required_skills', sa.Text(), nullable=False),
    sa.Column('experience_required', sa.String(length=255), nullable=True),
    sa.Column('education_required', sa.String(length=255), nullable=True),
    sa.Column('responsibilities', sa.Text(), nullable=True),
    sa.Column('benefits', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('employer_id', sa.Integer(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('embedding', sa.Text(), nullable=True),
    sa.Column('embedding_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_id'), 'jobs', ['id'], unique=False)


def _create_user_profiles() -> None:
    op.create_table('user_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('company_size', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('linkedin', sa.String(), nullable=True),
    sa.Column('twitter', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )


def _create_analyses() -> None:
    op.create_table('analyses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cv_id', sa.Integer(), nullable=False),
    sa.Column('job_title', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('job_description', sa.Text(), nullable=False),
    sa.Column('match_score', sa.Integer(), nullable=False),
    sa.Column('matched_skills', sa.Text(), nullable=False),
    sa.Column('missing_skills', sa.Text(), nullable=False),
    sa.Column('experience_match', sa.Integer(), nullable=True),
    sa.Column('education_match', sa.Integer(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cv_id'], ['cvs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )


def _create_applications() -> None:
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('match_score', sa.Integer(), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_id'), 'applications', ['id'], unique=False)


def _create_interviews() -> None:
    op.create_table('interviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employer_id', sa.Integer(), nullable=False),
    sa.Column('candidate_user_id', sa.Integer(), nullable=False),
    sa.Column('cv_id', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('meeting_url', sa.Text(), nullable=True),
    sa.Column('dial_in', sa.String(length=64), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=64), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['cv_id'], ['cvs.id'], ),
    sa.ForeignKeyConstraint(['employer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interviews_candidate_user_id'), 'interviews', ['candidate_user_id'], unique=False)
    op.create_index(op.f('ix_interviews_employer_id'), 'interviews', ['employer_id'], unique=False)
    op.create_index(op.f('ix_interviews_id'), 'interviews', ['id'], unique=False)


def _create_messages() -> None:
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_index(op.f('ix_messages_recipient_id'), 'messages', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_messages_sender_id'), 'messages', ['sender_id'], unique=False)


def _create_saved_jobs() -> None:
    op.create_table('saved_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('saved_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_jobs_id'), 'saved_jobs', ['id'], unique=False)


# One function per table, in foreign-key order (a table is created after the
# tables it points at). Split this way so migrate.py can also create a single
# missing table exactly as this baseline defines it, when catching up a
# database that predates migrations.
BASELINE_TABLES = {
    "users": _create_users,
    "cvs": _create_cvs,
    "jobs": _create_jobs,
    "user_profiles": _create_user_profiles,
    "analyses": _create_analyses,
    "applications": _create_applications,
    "interviews": _create_interviews,
    "messages": _create_messages,
    "saved_jobs": _create_saved_jobs,
}


def upgrade() -> None:
    """Create every baseline table."""
    for create in BASELINE_TABLES.values():
        create()


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_jobs_id'), table_name='saved_jobs')
    op.drop_table('saved_jobs')
    op.drop_index(op.f('ix_messages_sender_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_recipient_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_interviews_id'), table_name='interviews')
    op.drop_index(op.f('ix_interviews_employer_id'), table_name='interviews')
    op.drop_index(op.f('ix_interviews_candidate_user_id'), table_name='interviews')
    op.drop_table('interviews')
    op.drop_index(op.f('ix_applications_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_table('analyses')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_jobs_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_cvs_id'), table_name='cvs')
    op.drop_table('cvs')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
