"""auth tokens and session versioning

Adds what password reset and email verification need:

* ``auth_tokens`` -- one-time links, stored as SHA-256 hashes.
* ``user_profiles.token_version`` -- part of every login token; raising it
  signs the account out everywhere (done on password reset). The server
  default of 0 gives every existing account version 0, which is what tokens
  issued before this migration implicitly carry, so nobody is logged out.
* ``user_profiles.email_verified_at`` -- when the address was confirmed.

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-12 11:34:41.143436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_tokens_token_hash'), 'auth_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_auth_tokens_user_id'), 'auth_tokens', ['user_id'], unique=False)
    op.add_column('user_profiles', sa.Column('token_version', sa.Integer(), server_default='0', nullable=False))
    op.add_column('user_profiles', sa.Column('email_verified_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'email_verified_at')
    op.drop_column('user_profiles', 'token_version')
    op.drop_index(op.f('ix_auth_tokens_user_id'), table_name='auth_tokens')
    op.drop_index(op.f('ix_auth_tokens_token_hash'), table_name='auth_tokens')
    op.drop_table('auth_tokens')
    # ### end Alembic commands ###
