"use client";

import { useEffect, useState, useRef } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { apiCall } from "@/components/api";
import { describeApiError } from "@/components/format";
import { motion, AnimatePresence } from "framer-motion";
import { FaBookOpen, FaRobot, FaUser, FaArrowRight, FaPaperPlane, FaLightbulb } from "react-icons/fa";
import MessageDialog from "@/components/MessageDialog";

interface Source {
  type: "cv" | "job" | "market";
  label: string;
  ref: number | null;
  detail: string;
}

interface Message {
  id: string;
  role: "user" | "assistant";
  content: string;
  /** What the answer was grounded in. Absent for user messages. */
  sources?: Source[];
  /** "model" when generated by the LLM, "rules" for the deterministic path. */
  generatedBy?: string;
  /** Documentation for the skill gaps this answer named. */
  links?: { skill: string; title: string; url: string }[];
}

const SUGGESTED_QUESTIONS = [
  "What are my top skills?",
  "How can I improve my profile?",
  "What skills am I missing for tech roles?",
  "How is my experience section?",
];

export default function CareerLensPage() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const [messages, setMessages] = useState<Message[]>([
    {
      id: "welcome",
      role: "assistant",
      content: "Hi! I'm CareerLens, your AI career assistant. Ask me anything about your profile, skills, or career growth. What would you like to know?",
    },
  ]);
  const [input, setInput] = useState("");
  const [loading, setLoading] = useState(false);
  const [cvId, setCvId] = useState<string | null>(searchParams.get("cv_id"));
  const [dialog, setDialog] = useState({ open: false, title: '', message: '', type: 'info' as 'info' | 'success' | 'error' | 'warning' });
  const messagesEndRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages]);

  const handleSend = async (text?: string) => {
    const message = text || input.trim();
    if (!message) return;

    const userMessage: Message = {
      id: `user-${Date.now()}`,
      role: "user",
      content: message,
    };

    setMessages((prev) => [...prev, userMessage]);
    setInput("");
    setLoading(true);

    try {
      const payload: Record<string, unknown> = { message };
      if (cvId) payload.cv_id = cvId;

      const response = await apiCall("/api/career-lens/chat", {
        method: "POST",
        body: JSON.stringify(payload),
      });

      const data = await response.json();
      if (response.ok) {
        const assistantMessage: Message = {
          id: `assistant-${Date.now()}`,
          role: "assistant",
          content: data.response,
          sources: data.sources ?? [],
          generatedBy: data.generated_by,
          links: data.links ?? [],
        };
        setMessages((prev) => [...prev, assistantMessage]);
      } else {
        setDialog({ open: true, title: 'Error', message: describeApiError(data, "Failed to get response"), type: 'error' });
      }
    } catch (err) {
      setDialog({ open: true, title: 'Error', message: err instanceof Error ? err.message : "Error sending message", type: 'error' });
    } finally {
      setLoading(false);
    }
  };

  const handleKeyPress = (e: React.KeyboardEvent) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      handleSend();
    }
  };

  return (
    <div className="min-h-screen bg-neutral-900 text-neutral-50 flex flex-col">
      <div className="max-w-4xl mx-auto w-full px-4 sm:px-6 lg:px-8 py-8 flex-1 flex flex-col">
        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="flex items-center justify-between mb-6"
        >
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-lg bg-gradient-to-br from-blue-600 to-emerald-500 flex items-center justify-center">
              <FaRobot className="w-5 h-5 text-white" />
            </div>
            <div>
              <h1 className="page-title">CareerLens Chat</h1>
              <p className="text-sm text-neutral-400">Your AI career assistant</p>
            </div>
          </div>
          <motion.button
            onClick={() => router.push("/analyze")}
            className="btn-secondary text-sm"
            whileHover={{ scale: 1.02 }}
            whileTap={{ scale: 0.98 }}
          >
            Back to Profile
          </motion.button>
        </motion.div>

        {/* Chat Messages */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.1 }}
          className="flex-1 overflow-y-auto rounded-lg bg-neutral-800/50 border border-neutral-700/50 p-4 mb-4 min-h-[400px] max-h-[600px]"
        >
          <div className="space-y-4">
            <AnimatePresence>
              {messages.map((msg) => (
                <motion.div
                  key={msg.id}
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, y: -10 }}
                  className={`flex gap-3 ${msg.role === "user" ? "justify-end" : "justify-start"}`}
                >
                  {msg.role === "assistant" && (
                    <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-blue-600 to-emerald-500 flex items-center justify-center flex-shrink-0">
                      <FaRobot className="w-4 h-4 text-white" />
                    </div>
                  )}
                  <div
                    className={`max-w-[80%] rounded-lg px-4 py-3 ${
                      msg.role === "user"
                        ? "bg-blue-600 text-white"
                        : "bg-neutral-700/50 text-neutral-200 border border-neutral-600/30"
                    }`}
                  >
                    <p className="text-sm leading-relaxed">{msg.content}</p>

                    {/* Somewhere to start on each gap the answer named.
                        A gap without a next step is just bad news. */}
                    {msg.role === "assistant" &&
                      msg.links &&
                      msg.links.length > 0 && (
                        <div className="mt-3 pt-3 border-t border-neutral-600/30">
                          <p className="eyebrow mb-2">Start here</p>
                          <div className="flex flex-col gap-1.5">
                            {msg.links.map((l) => (
                              <a
                                key={l.url}
                                href={l.url}
                                target="_blank"
                                rel="noopener noreferrer"
                                className="text-[0.8125rem] text-neutral-300 hover:text-white transition-colors underline decoration-neutral-600 underline-offset-2"
                              >
                                {l.skill}: {l.title}
                              </a>
                            ))}
                          </div>
                        </div>
                      )}

                    {msg.role === "assistant" &&
                      msg.sources &&
                      msg.sources.length > 0 && (
                        <SourceList
                          sources={msg.sources}
                          generatedBy={msg.generatedBy}
                          onOpenJob={(id) => router.push(`/jobs/${id}`)}
                        />
                      )}
                  </div>
                  {msg.role === "user" && (
                    <div className="w-8 h-8 rounded-lg bg-neutral-700 flex items-center justify-center flex-shrink-0">
                      <FaUser className="w-4 h-4 text-neutral-300" />
                    </div>
                  )}
                </motion.div>
              ))}
            </AnimatePresence>
            {loading && (
              <motion.div
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                className="flex gap-3 justify-start"
              >
                <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-blue-600 to-emerald-500 flex items-center justify-center flex-shrink-0">
                  <FaRobot className="w-4 h-4 text-white" />
                </div>
                <div className="rounded-lg px-4 py-3 bg-neutral-700/50 border border-neutral-600/30">
                  <div className="flex gap-1">
                    <div className="w-2 h-2 bg-neutral-400 rounded-full animate-bounce" style={{ animationDelay: "0ms" }} />
                    <div className="w-2 h-2 bg-neutral-400 rounded-full animate-bounce" style={{ animationDelay: "150ms" }} />
                    <div className="w-2 h-2 bg-neutral-400 rounded-full animate-bounce" style={{ animationDelay: "300ms" }} />
                  </div>
                </div>
              </motion.div>
            )}
            <div ref={messagesEndRef} />
          </div>
        </motion.div>

        {/* Suggested Questions */}
        {messages.length <= 2 && (
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.2 }}
            className="mb-4"
          >
            <p className="text-sm text-neutral-400 mb-2 flex items-center gap-2">
              <FaLightbulb className="w-4 h-4 text-amber-400" />
              Suggested questions:
            </p>
            <div className="flex flex-wrap gap-2">
              {SUGGESTED_QUESTIONS.map((question, i) => (
                <button
                  key={i}
                  onClick={() => handleSend(question)}
                  className="text-sm px-3 py-2 rounded-lg bg-neutral-800 border border-neutral-700/50 text-neutral-300 hover:border-blue-500/30 hover:text-blue-400 transition-colors"
                >
                  {question}
                </button>
              ))}
            </div>
          </motion.div>
        )}

        {/* Input */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.3 }}
          className="flex gap-2"
        >
          <input
            type="text"
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onKeyPress={handleKeyPress}
            placeholder="Ask about your skills, experience, or career advice..."
            className="flex-1 px-4 py-3 bg-neutral-800 border border-neutral-700 rounded-lg text-neutral-100 placeholder:text-neutral-500 focus:outline-none focus:ring-2 focus:ring-blue-500/50 focus:border-blue-500/50"
          />
          <motion.button
            onClick={() => handleSend()}
            disabled={!input.trim() || loading}
            className="px-4 py-3 bg-blue-600 text-white rounded-lg hover:bg-blue-700 disabled:opacity-50 flex items-center gap-2"
            whileHover={{ scale: 1.02 }}
            whileTap={{ scale: 0.98 }}
          >
            <FaPaperPlane className="w-4 h-4" />
          </motion.button>
        </motion.div>

        <MessageDialog
          open={dialog.open}
          onClose={() => setDialog({ ...dialog, open: false })}
          title={dialog.title}
          message={dialog.message}
          type={dialog.type}
        />
      </div>
    </div>
  );
}

/**
 * Shows what an answer was built from. The assistant is only allowed to use
 * retrieved CareerLens data, so every claim it makes traces back to one of
 * these rows -- job sources link straight to the posting.
 */
function SourceList({
  sources,
  generatedBy,
  onOpenJob,
}: {
  sources: Source[];
  generatedBy?: string;
  onOpenJob: (id: number) => void;
}) {
  const [open, setOpen] = useState(false);

  return (
    <div className="mt-3 pt-3 border-t border-neutral-700">
      <button
        onClick={() => setOpen(!open)}
        className="flex items-center gap-1.5 text-xs text-neutral-400 hover:text-neutral-200 transition-colors"
        aria-expanded={open}
      >
        <FaBookOpen className="w-3 h-3" />
        {open ? "Hide" : "Show"} sources ({sources.length})
        {generatedBy === "rules" && (
          <span className="ml-1 text-neutral-500">· offline mode</span>
        )}
      </button>

      {open && (
        <ul className="mt-2 space-y-1.5">
          {sources.map((src, i) => (
            <li key={i} className="flex items-start gap-2 text-xs">
              <span
                className={
                  src.type === "job"
                    ? "chip-accent shrink-0"
                    : src.type === "cv"
                      ? "chip-positive shrink-0"
                      : "chip shrink-0"
                }
              >
                {src.type}
              </span>
              {src.type === "job" && src.ref !== null ? (
                <button
                  onClick={() => onOpenJob(src.ref as number)}
                  className="text-left text-neutral-300 hover:text-white underline underline-offset-2"
                >
                  {src.label}
                </button>
              ) : (
                <span className="text-neutral-300">{src.label}</span>
              )}
              {src.detail && (
                <span className="text-neutral-500 shrink-0">{src.detail}</span>
              )}
            </li>
          ))}
        </ul>
      )}
    </div>
  );
}
